/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as ReportsReportIdPresentRouteImport } from './routes/reports.$reportId.present'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdPresentRoute = ReportsReportIdPresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => ReportsReportIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/reports/$reportId': typeof ReportsReportIdRouteWithChildren
  '/reports/': typeof ReportsIndexRoute
  '/reports/$reportId/present': typeof ReportsReportIdPresentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/reports/$reportId': typeof ReportsReportIdRouteWithChildren
  '/reports': typeof ReportsIndexRoute
  '/reports/$reportId/present': typeof ReportsReportIdPresentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/reports/$reportId': typeof ReportsReportIdRouteWithChildren
  '/reports/': typeof ReportsIndexRoute
  '/reports/$reportId/present': typeof ReportsReportIdPresentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge-base'
    | '/settings'
    | '/reports/$reportId'
    | '/reports/'
    | '/reports/$reportId/present'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/knowledge-base'
    | '/settings'
    | '/reports/$reportId'
    | '/reports'
    | '/reports/$reportId/present'
  id:
    | '__root__'
    | '/'
    | '/knowledge-base'
    | '/settings'
    | '/reports/$reportId'
    | '/reports/'
    | '/reports/$reportId/present'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  SettingsRoute: typeof SettingsRoute
  ReportsReportIdRoute: typeof ReportsReportIdRouteWithChildren
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId/present': {
      id: '/reports/$reportId/present'
      path: '/present'
      fullPath: '/reports/$reportId/present'
      preLoaderRoute: typeof ReportsReportIdPresentRouteImport
      parentRoute: typeof ReportsReportIdRoute
    }
  }
}

interface ReportsReportIdRouteChildren {
  ReportsReportIdPresentRoute: typeof ReportsReportIdPresentRoute
}

const ReportsReportIdRouteChildren: ReportsReportIdRouteChildren = {
  ReportsReportIdPresentRoute: ReportsReportIdPresentRoute,
}

const ReportsReportIdRouteWithChildren = ReportsReportIdRoute._addFileChildren(
  ReportsReportIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  SettingsRoute: SettingsRoute,
  ReportsReportIdRoute: ReportsReportIdRouteWithChildren,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
